version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ant
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mobiles_db
    ports:
      - "6543:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ant@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "15432:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin:/var/lib/pgadmin

  liquibase:
    container_name: liquibase
    restart: on-failure
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
      - ./Mobiles Dataset (2025).csv:/liquibase/Mobiles Dataset (2025).csv
    environment:
      LIQUIBASE_SEARCH_PATH: ./changelog
    build:
      dockerfile: liquibase/Dockerfile
    command: liquibase --url="jdbc:postgresql://postgres:5432/mobiles_db" --changeLogFile=liquibase-changelog.xml --username=ant --password=postgres update
    depends_on:
      - postgres

volumes:
  postgres_data: